
#
# Current setup:
# - All development is done in a fork.
# - Pull requests are merged into master and it auto publishes to the myget pre-release 'pk-development' feed.
# - To publish a live NuGet package, create a tag on master branch.
#

version: '{build}.0.0-dev'
configuration: Release
os: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
environment:
  project_name: HttpClient.Helpers
  solution_file: HttpClient.Helpers\HttpClient.Helpers.sln

# Override the 'version' if this is a GH-tag-commit -or- this is a custom branch (i.e not 'master').
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq $TRUE -and $env:APPVEYOR_REPO_BRANCH -eq 'master')
      { 
          Write-Host " !! Commit is Tagged and branch is 'master' - forcing build version to tag-value." -ForegroundColor Red; 
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/f5b40256fc2ca77d49f1c7773d28406152544c1e/appveyor-build-info.ps'))
                                       
before_build:
  - cmd: dotnet restore 

build_script:
  - cmd: dotnet build 

test_script:
  - cmd dotnet test tests\HttpClient.Helpers.Tests\HttpClient.Helpers.Tests.csproj

cache:
  - packages -> **\packages.config
